# FROM httpd:2.4
# RUN rm /bin/sh && ln -s /bin/bash /bin/sh
# RUN mkdir /root/frontend
# WORKDIR /root/frontend
# COPY ./frontend /root/frontend
# RUN apt-get -y update && apt-get -y install wget && apt-get -y install git
# RUN wget -O- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
# RUN source ~/.bashrc && nvm install 10.21.0 && npm install && npm run build
# RUN cp -R build/* /usr/local/apache2/htdocs/

FROM node:16 as build-deps
RUN mkdir /root/frontend
WORKDIR /root/frontend
COPY ./frontend /root/frontend
RUN yarn
RUN yarn build