version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "naturefitness"
      MYSQL_USER: "lorax"
      MYSQL_PASSWORD: "lorax"
      MYSQL_ROOT_PASSWORD: "lorax"
    ports:
      - "3306:3306"

  front:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/.next/
